### PR TITLE
tasks: support customised user model

### PR DESCRIPTION
**Pull request by noirbee**
Go through django.contrib.auth.get_user_model() instead of a direct model import.

### CODE REVIEW

**Comment by Alir3z4** [comment]
@noirbee Thanks for the patch, good catch.
Could you please update the CHANGELOG file as well ?
Once updated, I will merge and cut a release soon.

**Comment by Alir3z4** [comment]
Thanks, for the update.
I've approved the changes.

Is there anything left that you want to push ?

**Comment by noirbee** [comment]
Thanks, no more changes from me !

**Comment by Alir3z4** [comment]
Great, let's get it merged.

**Pull request merged**
