### PR TITLE
Django1.10

### PR DESCRIPTION
**Pull request by arianerocha**
**django 1.10 branch** with only a few changes to make django-plans compatible with django 1.10 and translations to pt_BR

### CODE REVIEW

**Comment by hitminion** [comment]
@cypreess take a look please

**Comment by cypreess** [comment]
@arianerocha could you look is there any changes needed for 1.11 support? Could you also fix things changed in setup.py (repo url)

**Comment by arianerocha** [comment]
Sure @cypreess! I'll check and fix setup.py

**Comment by Alir3z4** [comment]
Pull request https://github.com/cypreess/django-plans/pull/56 is newer and fixes this already.

**Pull request closed without merging**
