### PR TITLE
 Migrated to Django 2.0.2

### PR DESCRIPTION
**Pull request by Nuurek**

### CODE REVIEW

**Comment by cypreess** [comment]
@Alir3z4 I vote for merging this change and bumping version to 2.0.0 for the compatibility with new django and dropping support for old python.

**Comment by Alir3z4** [comment]
This is good.
It has my vote too.
I agree with dropping the old version as well.

**Comment by Alir3z4** [comment]
This is good by now.
Do you have anything else to push @Nuurek ?

@cypreess It looks good to me and I gave LGTM, once you have reviewed and approved we can merge.

**Comment by Nuurek** [comment]
@Alir3z4 just these. I've got other commits in my fork but they don't add anything more related to Django 2.0 migration. However, I think that you should change the version.

**Comment by Alir3z4** [comment]
@Nuurek that's great, thanks for letting me know.
Once it's approved by @cypreess we can go ahead and merge.

**Comment by Alir3z4** [comment]
@cypreess if this is good by you, let's merge it

@Nuurek can you explain the new changes please before we do a final review ?

**Comment by Nuurek** [comment]
I've already edited the source branch of this PR with changes that shouldn't be there. My bad.
Because I can't change source branch of this PR, I've created a new one with some explanations, pointing to correct source branch: https://github.com/cypreess/django-plans/pull/67

Sorry for an inconvenience.

**Comment by Alir3z4** [comment]
@Nuurek thanks for taking care of it and clean pull request.
I'll review right away

**Pull request closed without merging**
